title: Camille COCHENER
logo: /assets/img/logo.png
description: Data Scientist
school: Agrocampus Ouest & Télécom Paris Alumni
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
location : "Paris"
links:
  - label: "Linkedin"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/camillecochener/"
  - label: "Mail"
    icon: "fas fa-envelope"
    url: "mailto:cochenercamille@yahoo.fr"
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/camillecochener"
  - label: "Resume"
    icon: "fas fa-file"
    url: "assets/files/CV_CamilleCOCHENER_EN.pdf"
