title: Camille COCHENER
logo: /assets/img/logo.png
description: Data Scientist with 4 years of experience - Agrocampus Ouest & Télécom Paris Alumni
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
